var variables = {"alimentacion":[
    {
        "desc": "Número total de alumnos",
        "variable": "2"
    }],
                 "p1":[
                     {"desc": "Preescolar",
                      "variable": "2"},
                     {"desc": "Primaria",
                      "variable": "3"},
                     {"desc": "Secundaria",
                      "variable": "4"},
                     {"desc": "CAM",
                      "variable": "7"}
                 ],
                 "p2":[
                      {"desc": "General",
                      "variable": "1"},
                     {"desc": "Secundaria técnica",
                      "variable": "2"},
                     {"desc": "Telesecundaria",
                      "variable": "3"},
                     {"desc": "Secundaria para trabajadores",
                      "variable": "4"},
                     {"desc": "Indígena",
                      "variable": "5"}                    
                 ],
                 "p80":[
                      {"desc": "Matutino",
                      "variable": "1"},
                     {"desc": "Vespertino",
                      "variable": "2"},
                     {"desc": "Nocturno",
                      "variable": "3"},
                     {"desc": "Discontinuo",
                      "variable": "4"},
                     {"desc": "Continuo, tiempo completo",
                      "variable": "5"},
                     {"desc": "Continuo, jornada ampliada",
                      "variable": "6"},
                     {"desc": "Complementario",
                      "variable": "7"} 
                 ],
                  "p7":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "t"}
                 ],
		"p81":[
                      {"desc": "PÚBLICO",
                      "variable": "1"},
                     {"desc": "Privado",
                      "variable": "2"}
                 ],
                 "p9":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "t"}
                 ],
		"p8":[
                      {"desc": "De 0 a 6",
                      "variable": "1"},
                     {"desc": "De 7 a 14",
                      "variable": "2"},
                     {"desc": "De 15 a 24",
                      "variable": "3"},
		     {"desc": "Mas de 25",
                      "variable": "4"}
                 ],
		"p11":[
                      {"desc": "SIN ESCOLARIDAD",
                      "variable": "1"},
                     {"desc": "PRIMARIA",
                      "variable": "2"},
                     {"desc": "ESTUDIOS TÉCNICOS O COMERCIALES CON PRIMARIA TERMINADA",
                      "variable": "3"},
                     {"desc": "SECUNDARIA",
                      "variable": "4"},
                     {"desc": "PROFESIONAL TÉCNICO",
                      "variable": "5"},
                     {"desc": "PREPARATORIA O BACHILLERATO",
                      "variable": "6"},
                     {"desc": "TÉCNICO SUPERIOR",
                      "variable": "7"},
                     {"desc": "NORMAL PREESCOLAR",
                      "variable": "8"},
		     {"desc": "NORMAL PRIMARIA",
                      "variable": "9"},
                     {"desc": "NORMAL SUPERIOR (LICENCIATURA)",
                      "variable": "10"},
                     {"desc": "LICENCIATURA",
                      "variable": "11"},
                     {"desc": "MAESTRÍA",
                      "variable": "12"},
                     {"desc": "DOCTORADO",
                      "variable": "13"},
                     {"desc": "NO ESPECIFICADO",
                      "variable": "14"},
                     {"desc": "SIN INFORMACIÓN (NO APLICA)",
                      "variable": "xxxxx"} 
                 ],
                  "p10":[
                      {"desc": "Caminando",
                      "variable": "1"},
                     {"desc": "Transporte público",
                      "variable": "2"},
                     {"desc": "Transporte escolar",
                      "variable": "3"},
                     {"desc": "Automóvil o camioneta",
                      "variable": "4"},
                     {"desc": "Bicicleta",
                      "variable": "5"},
                     {"desc": "Motocicleta",
                      "variable": "6"},
                     {"desc": "Panga o lancha",
                      "variable": "7"},
                     {"desc": "Caballo, burro, mula, etc.",
                      "variable": "8"} 
                 ],
                 "p12":[
                      {"desc": "No recibe becas ni apoyo a la educación",
                      "variable": "1"},
                     {"desc": "Beca de apoyo a la educación básica de madres jóvenes y jóvenes embarazadas (PROMAJOVEN)",
                      "variable": "2"},
                     {"desc": "Beca oportunidades",
                      "variable": "3"},
                     {"desc": "Beca para personas con discapacidad",
                      "variable": "4"},
                     {"desc": "Beca acércate a tu escula (CONAFE antes FIDUCAR)",
                      "variable": "5"},
                     {"desc": "Beca del gobierno estatal o del Distrito Federal",
                      "variable": "6"},
                     {"desc": "Beca de fundaciones o instituciones privadas ",
                      "variable": "7"},
                     {"desc": "Beca de escuela particular",
                      "variable": "8"},
                     {"desc": "Programa de educación primaria para niñas y niños migrantes (PRONIM) ",
                      "variable": "9"},
                     {"desc": "Si recibe beca o apoyo, pero no sabe quien lo otorga",
                      "variable": "10"} 
                 ],
                  "p13":[
                      {"desc": "TITULADO",
                      "variable": "1"},
                     {"desc": "TÍTULO EN TRÁMITE",
                      "variable": "2"},
                     {"desc": "PASANTE",
                      "variable": "3"},
                     {"desc": "ESTUDIOS INCONCLUSOS O CONTINÚA ESTUDIANDO",
                      "variable": "4"},
                     {"desc": "SIN INFORMACIÓN (NO APLICA)",
                      "variable": "xxxxx"}
                 ],
                 "p14":[
                      {"desc": "PÚBLICA?",
                      "variable": "1"},
                     {"desc": "PRIVADA?",
                      "variable": "2"},
                     {"desc": "NO ESPECIFICADO",
                      "variable": "9"},
                     {"desc": "SIN INFORMACIÓN (NO APLICA)",
                      "variable": "xxxxx"}      
                 ],
                  "p15":[
                      {"desc": "Si",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin informacion",
                      "variable": "xxxxx"}                    
                 ],
                 "p16":[
                      {"desc": "PRIMARIA",
                      "variable": "1"},
                     {"desc": "ESTUDIOS TÉCNICOS O COMERCIALES CON PRIMARIA TERMINADA	",
                      "variable": "2"},
                     {"desc": "SECUNDARIA",
                      "variable": "3"},
                     {"desc": "PROFESIONAL TÉCNICO",
                      "variable": "4"},
                     {"desc": "PREPARATORIA O BACHILLERATO",
                      "variable": "5"},
                     {"desc": "TÉCNICO SUPERIOR",
                      "variable": "6"},
                     {"desc": "NORMAL PREESCOLAR",
                      "variable": "7"},
                     {"desc": "NORMAL PRIMARIA",
                      "variable": "8"},
                     {"desc": "NORMAL SUPERIOR (LICENCIATURA)",
                      "variable": "9"},
                     {"desc": "LICENCIATURA",
                      "variable": "10"} ,
                     {"desc": "MAESTRÍA",
                      "variable": "11"},
                     {"desc": "DOCTORADO",
                      "variable": "12"},
                     {"desc": "CURSOS, DIPLOMADOS, CERTIFICACIONES U OTROS",
                      "variable": "13"},
                     {"desc": "SIN INFORMACIÓN (NO APLICA)",
                      "variable": "xxxxx"} 
                 ],
		"p17":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p18":[
                      {"desc": "INSTITUCIÓN EN LA QUE ESTUDIA",
                      "variable": "1"},
                     {"desc": "FEDERAL",
                      "variable": "2"},
                     {"desc": "ESTATAL",
                      "variable": "3"},
                     {"desc": "FUNDACIÓN O INSTITUCIÓN PRIVADA",
                      "variable": "4"},
                     {"desc": "INTERNACIONAL",
                      "variable": "5"},
                     {"desc": "SINDICAL",
                      "variable": "6"},
                     {"desc": "OTRO",
                      "variable": "7"},
                     {"desc": "SIN INFORMACIÓN (NO APLICA)",
                      "variable": "xxxxx"}
                 ],
		"p20":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p22":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p24":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p25":[
                      {"desc": "MAESTRO FRENTE A GRUPO",
                      "variable": "1"},
                     {"desc": "MAESTRO DE APOYO A LA LABOR EDUCATIVA",
                      "variable": "2"},
                     {"desc": "APOYO A LA LABOR EDUCATIVA (PSICÓLOGO, TRABAJADOR SOCIAL, ASISTENTE DE LABORATORIO, TERAPEUTA, NUTRIÓLOGO, TUTOR, ENTRE OTROS)",
                      "variable": "3"},
                     {"desc": "COORDINADOR ACADÉMICO",
                      "variable": "4"},
                     {"desc": "DIRECTOR CON GRUPO",
                      "variable": "5"},
                     {"desc": "DIRECTOR DE ESCUELA (SIN GRUPO)",
                      "variable": "6"},
                     {"desc": "SUBDIRECTOR DE ESCUELA",
                      "variable": "7"},
                     {"desc": "JEFE DE ENSEÑANZA",
                      "variable": "8"},
                     {"desc": "SUPERVISOR DE ZONA O JEFE DE SECTOR",
                      "variable": "9"},
                     {"desc": "MANDO MEDIO O SUPERIOR",
                      "variable": "10"} ,
                     {"desc": "PREFECTO",
                      "variable": "11"},
                     {"desc": "ASESOR TÉCNICO PEDAGÓGICO",
                      "variable": "12"},
                     {"desc": "COORDINADOR O ASESOR ACADÉMICO DE LA DIVERSIDAD SOCIAL",
                      "variable": "13"},
                     {"desc": "ADMINISTRATIVO",
                      "variable": "14"},
                     {"desc": "PERSONAL DE SERVICIOS",
                      "variable": "15"},
                     {"desc": "CONSERJE O INTENDENTE",
                      "variable": "16"} 
                 ],
		"p26":[
                      {"desc": "BASE",
                      "variable": "1"},
                     {"desc": "CONFIANZA",
                      "variable": "2"},
                     {"desc": "INTERINO",
                      "variable": "3"},
                     {"desc": "EVENTUAL",
                      "variable": "4"},
                     {"desc": "HONORARIOS O SUELDOS ASIMILADOS A SALARIOS",
                      "variable": "5"}
                 ],
		"p27":[
                      {"desc": "GOBIERNO O INSTITUCIONES PÚBLICAS FEDERALES",
                      "variable": "1"},
                     {"desc": "GOBIERNO O INSTITUCIONES PÚBLICAS ESTATALES",
                      "variable": "2"},
                     {"desc": "GOBIERNO MUNICIPAL",
                      "variable": "3"},
                     {"desc": "SOCIEDAD DE PADRES DE FAMILIA O CONSEJO DE PARTICIPACIÓN SOCIAL",
                      "variable": "4"},
                     {"desc": "ESCUELA PRIVADA",
                      "variable": "5"},
                     {"desc": "FUNDACIÓN PRIVADA",
                      "variable": "6"},
                     {"desc": "INSTITUCIÓN AUTÓNOMA",
                      "variable": "7"}
                 ],
		"p28":[
                      {"desc": "De 0 a 2",
                      "variable": "1"},
                     {"desc": "De 3 a 5",
                      "variable": "2"},
                     {"desc": "Mas de 5",
                      "variable": "3"}
                 ],
		"p31":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p33":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p35":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p40":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p41":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p43":[
                      {"desc": "1",
                      "variable": "1"},
                     {"desc": "2",
                      "variable": "2"},
		      {"desc": "3",
                      "variable": "3"},
                     {"desc": "4",
                      "variable": "4"},
                     {"desc": "Mas de 5",
                      "variable": "5"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p44":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ],
		"p45":[
                      {"desc": "Sí",
                      "variable": "1"},
                     {"desc": "No",
                      "variable": "2"},
                     {"desc": "Sin información",
                      "variable": "xxxxx"}
                 ]
                     
                
                     
                     
                 
                     
                   
                     
                       

        
};
       
